package views.screen.rentbike;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

public class RentBikeScreenHandler {
	@FXML
	private Button rentbtn;
	@FXML
	private TextArea bike_code;

	// Event Listener on Button[#rentbtn].onMouseClicked
	@FXML
	public void onRentBtnClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
