package views.screen.payment;

import javafx.fxml.FXML;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class PaymentScreenHandler {
	@FXML
	private ImageView bike_image;
	@FXML
	private Label bike_code;
	@FXML
	private Label bike_name;
	@FXML
	private Label rent_fee;
	@FXML
	private Label bonus_fee;
	@FXML
	private Label start_rent_time;
	@FXML
	private Label first_money;
	@FXML
	private TextArea card_code;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void onConfirmbtnClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
