package views.screen.payment;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class ResultScreenHandler {
	@FXML
	private Button confirmbtn;

	// Event Listener on Button[#confirmbtn].onMouseClicked
	@FXML
	public void onConfirmbtnClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
