package views.screen.home;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import controller.HomeController;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import utils.Utils;
import views.screen.BaseScreenHandler;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class HomeScreenHandler extends BaseScreenHandler implements Initializable {

    public static Logger LOGGER = Utils.getLogger(HomeScreenHandler.class.getName());

	@FXML
	private TextArea search;
	@FXML
	private ImageView qr;
	@FXML
	private ImageView map_test_image;
	@FXML
	private Button test_place;
	@FXML
	private AnchorPane view_bike_pop_up;
	@FXML
	private Label dock_name;
	@FXML
	private Label dock_address;
	@FXML
	private Label dock_square;
	@FXML
	private Label number_of_bike;
	@FXML
	private Label number_of_electro_bike;
	@FXML
	private Label number_of_couple_bike;
	@FXML
	private Label bike_space;
	@FXML
	private Label electro_bike_space;
	@FXML
	private Label couple_bike_space;
	@FXML
	private Label distance;
	@FXML
	private Label walk_time;
	@FXML
	private Label motorbike_time;
	@FXML
	private Label car_time;
	@FXML
	private Button view_detail;
	
	public HomeScreenHandler(Stage stage, String screenPath) throws IOException {
		super(stage, screenPath);
		// TODO Auto-generated constructor stub
	}
	public HomeController getBController() {
        return (HomeController) super.getBController();
    }
	// Event Listener on TextArea[#search].onMouseClicked
	@FXML
	public void onSearchClick(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#test_place].onMouseClicked
	@FXML
	public void onTestPlacebtnClick(MouseEvent event) {
		view_bike_pop_up.setVisible(true);
	}
	// Event Listener on Button[#view_detail].onMouseClicked
	@FXML
	public void onViewDetailClick(MouseEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		setBController(new HomeController());
		map_test_image.setOnMouseClicked(e -> {
			view_bike_pop_up.setVisible(false);
        });
	}
}
