package views.screen.givebikeback;

import javafx.fxml.FXML;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class GiveBikeBackHandler {
	@FXML
	private ImageView bike_image;
	@FXML
	private Label bike_code;
	@FXML
	private Label bike_type;
	@FXML
	private Label rent_fee;
	@FXML
	private Label bonus_fee;
	@FXML
	private Label start_rent_time;
	@FXML
	private Label finish_rent_time;
	@FXML
	private Label total_time;
	@FXML
	private Label recipe;
	@FXML
	private Label total_fee;
	@FXML
	private Label first_money;
	@FXML
	private Label refund_money;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void onConfirmbtnClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
