package views.screen.givebikeback;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

public class PaymentFormHandler {
	@FXML
	private Label bike_code;
	@FXML
	private Label bike_type;
	@FXML
	private Label first_money;
	@FXML
	private Button confirmbtn;
	@FXML
	private Label total_fee;
	@FXML
	private Label card_code;
	@FXML
	private TextArea card_pin;
	@FXML
	private TextArea expired_date;

	// Event Listener on Button[#confirmbtn].onMouseClicked
	@FXML
	public void onConfirmbtnClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
